[package]
name = "algebra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "*"
rayon = "1.5.1"
num_cpus = "1.13.0" 
rand = "0.8"
[dev-dependencies]
criterion = "*"
